{% set name = "planet-auth" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/planet_auth-{{ version }}.tar.gz
  sha256: 6d82ce93a8011beb13eb65a6bb38b32891208e82523177282644dec12b95126e

build:
  entry_points:
    - plauth = planet_auth_utils.commands.cli.main:cmd_plauth
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - httpx
    - pyjwt
    - pyqrcode
    - requests
    - setuptools
    - strenum
    - click
    - prompt_toolkit
    # This is not in the metadata, but required.
    - cryptography

test:
  imports:
    - planet_auth
    - planet_auth_config_injection
    - planet_auth_utils
  commands:
    - pip check
    - plauth --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/planetlabs/planet-auth-python
  summary: Planet Auth Utility Code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
